name: covid_form
description: covid patient form flutter.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_gherkin: ^2.0.0
  flutter_lints: ^2.0.1
  path:
  glob:


flutter:
  uses-material-design: true

  assets:
  - assets/